controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_logout:
    path: /logout
    methods: GET

# config/routes.yaml
crea_quiz:
    path: /quiz/creer
    controller: App\Controller\QuizController::creaQuiz
    methods: ['GET', 'POST']

quiz_list:
    path: /quiz/list
    controller: App\Controller\QuizlistController::index

quiz_show:
    path: /quiz/detail_quiz/{id}
    controller: App\Controller\QuizlistController::quizdetail

correction_quiz:
    path: /quiz/{id}/copies
    controller: App\Controller\QuizlistController::correctionQuiz

liste_eleves:
    path: /liste_eleves
    controller: App\Controller\QuizlistController::listeEleves

